apiVersion: v2
name: mongodb #chart-name
description:  Helm chart for a Kubernetes mongodb application
type: application
version: 1.0.0  #This is Helm Chart version
appVersion: "1.31.6"  #this is our nginx application version only for reference