apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db                # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db              #has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: srikanth865/mongodb:{{ .Values.statefulset.imageVersion}}
        volumeMounts:
        - name: www
          mountPath: /data/db
  # PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi