apiVersion: v2
name: mongodb #chart-name
description:  Helm chart for a Kubernetes mongodb application
type: application
version: 0.1.0  #This is Helm Chart version
appVersion: v1  #this is our mongodb application version only for reference