apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
   # labels related to deployment resource just for reference
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
 replicas:  {{ .Values.deployment.replicas }}
 selector: #  which Pods the Deployment manages
    matchLabels:  #matchLabels is inside of selector because it contains the labels used to identify those Pods.
    #this labels is match the pod containers
        project: roboshop
        tier: backend
        component: catalogue
##its a pod defination
 template:
  metadata:
    labels:
       project: roboshop
       tier: backend
       component: catalogue
  spec:
   containers:
     - name: catalogue
       image: srikanth865/catalogue:{{ .Values.deployment.imageversion }}
       resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
       envFrom:
        - configMapRef:
           name: catalogue
      
---