apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
 # servicer labels  resource just for reference
 labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
 selector:
 #this selector  service labels going to match the catalogue pod labels
    project: roboshop
    tier: backend
    component: catalogue

 ports:  #ports expects a list, so we gik=ve like this - 
  - protocol: TCP
    port: 8080 #serviceport
    targetPort: 8080  #container port
---